title: "Architecture Tracer"
theme: minima

header_pages:
  - index.md
  - user-guide.md
  - developer-guide.md

markdown: kramdown

repository: "deltaminor/architecture-tracer"
github_icon: "images/github-icon.png"

plugins:
  - jemoji

exclude:
  - app/
  - Gemfile

keep_files:
  - app