title: "Architecture Tracer"
theme: minima

baseurl: "/architecture-tracer"

minima:
  skin: dark
  nav_pages:
    - user-guide.md
    - developer-guide.md

markdown: kramdown

repository: "deltaminor/architecture-tracer"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
  - jekyll-feed

keep_files:
  - app